site:
  title: My Project Docs
  start_page: myproject::index.adoc
  url: https://docs.example.com/

content:
  sources:
    - url: https://bitbucket.org/<workspace>/<repo>.git
      branches: [main]
      start_path: docs

ui:
  bundle:
    url: https://docs.example.com/ui-bundle.zip
    snapshot: true
